### ISSUE TITLE
Cara, esse projeto ficou excelente, parabéns!

### ISSUE THREAD

**Issue by djedu28** [vncsmnl/guiadoprogramador#4]
# Cara, esse projeto ficou excelente, parabéns!

## Pode adicionar nos ícones o [Lucide](https://lucide.dev/) 
[Lucide](https://lucide.dev/)  é uma biblioteca de ícones de `código aberto`. ela é uma ótima biblioteca de UI-icons leves, gratuitos e bonitos. Os pacotes estão disponíveis para diversas tecnologias, incluindo[ Web (Vanilla) ](https://lucide.dev/guide/packages/lucide),[ React ](https://lucide.dev/guide/packages/lucide-react),[ React Native ](https://lucide.dev/guide/packages/lucide-react-native),[ Vue ](https://lucide.dev/guide/packages/lucide-vue),[ Vue 3 ](https://lucide.dev/guide/packages/lucide-vue-next),[ Svelte ](https://lucide.dev/guide/packages/lucide-svelte),[ Preact ](https://lucide.dev/guide/packages/lucide-preact),[ Solid ](https://lucide.dev/guide/packages/lucide-solid),[ Angular ](https://lucide.dev/guide/packages/lucide-angular),[ NodeJS ](https://lucide.dev/guide/packages/lucide-static#nodejs)e[ Flutter ](https://lucide.dev/guide/packages/lucide-flutter).

## Recomendo dar o 🧡 para a rocketrseat, 
As imersões (gratuitas e completas) deles são ótimas e recentemente abriram o leque de áreas, tendo além do JavaScript, 
trilhas de 
* html + CSS + JS (iniciante),
* Python, 
* java, 
* C#, 
* e até devOps (avançado) (começando pela próxima NLW que é dia 1/abril a 4/abril/2024, [NLW unit](https://www.rocketseat.com.br/eventos/nlw?referral_id=luis-6269) (clica  [aqui](https://www.rocketseat.com.br/eventos/nlw?referral_id=luis-6269) para saber mais do evento)

![nlw unit](https://github.com/vncsmnl/guiadoprogramador/assets/43933482/7997616b-4451-4dd0-a7bc-bbd3735fb5f0)

**Comment by vncsmnl** [comment]
Obrigado pelo feedback, fiz o merge das suas contribuições.
